<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Jędrzej Bogacki"> <!-- update 2016: Kuba Rdzak -->
    <link rel="shortcut icon" href="favicon.png" type="image/x-icon"/>
      <meta name="robots" content="noindex, nofollow">

  <title><?php echo htmlspecialchars(implode(' - ', array_reverse($_config['title']))); ?></title>

<link href='https://fonts.googleapis.com/css?family=Montserrat|PT+Serif:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="css/bootstrap.css" rel="stylesheet">

<style>
    @import url('https://fonts.googleapis.com/css?family=Lato');
body { background-color:#333; }
#snow{
	background: none;
	font-family: Androgyne;
	background-image: url('http://www.wearewebstars.dk/codepen/img/s1.png'), url('http://www.wearewebstars.dk/codepen/img//s2.png'), url('http://www.wearewebstars.dk/codepen/img//s3.png');
	height: 100%;
	left: 0;
	position: absolute;
	top: 0;
	width: 100%;
	z-index:10000;
	-webkit-animation: snow 10s linear infinite;
	-moz-animation: snow 10s linear infinite;
	-ms-animation: snow 10s linear infinite;
	animation: snow 10s linear infinite;
}
@keyframes snow {
  0% {background-position: 0px 0px, 0px 0px, 0px 0px;}
  50% {background-position: 500px 500px, 100px 200px, -100px 150px;}
  100% {background-position: 500px 1000px, 200px 400px, -100px 300px;}
}
@-moz-keyframes snow {
  0% {background-position: 0px 0px, 0px 0px, 0px 0px;}
  50% {background-position: 500px 500px, 100px 200px, -100px 150px;}
  100% {background-position: 400px 1000px, 200px 400px, 100px 300px;}
}
@-webkit-keyframes snow {
  0% {background-position: 0px 0px, 0px 0px, 0px 0px;}
  50% {background-position: 500px 500px, 100px 200px, -100px 150px;}
  100% {background-position: 500px 1000px, 200px 400px, -100px 300px;}
}
@-ms-keyframes snow {
  0% {background-position: 0px 0px, 0px 0px, 0px 0px;}
  50% {background-position: 500px 500px, 100px 200px, -100px 150px;}
  100% {background-position: 500px 1000px, 200px 400px, -100px 300px;}
}

body{font-family: 'Lato', 'PT Serif', serif; color:#fff;}
.jumbotron h1{font-size:58px; font-family: 'Montserrat', 'Helvetica Neue', 'Arial', sans-serif;padding: 0; letter-spacing: .07em; }
.container{width:100%; height:100%; overflow:hidden; background:url('hero.jpg') no-repeat center; position: absolute; bottom:0; left:0; z-index:1999;    display: flex;
    align-items: center;
    justify-content: center;}

.container .jumbotron{
max-width: 980px;
text-align: center;
background: transparent;
border-radius: 0;
padding:50px 0;
	z-index:100000;
}
.row {padding:0 60px;}

.jumbotron form{text-align: center;}

.btn-lg
{
padding: 10px 26px;
font-size: 28px;}
.btn
 {
border-radius:0;

}
.btn-danger
{
background:#BB3E45;
}
.btn-danger:hover
{
background:#9D343A;
}

select {
  border: 1px solid #ddd;
  border-radius: 50%;
  -webkit-appearance: none;
  border-radius: 60px;
  -webkit-appearance: none;
  height: 60px;
  border-bottom-right-radius: 0;
  border-top-right-radius: 0;
  padding: 0 10px;
      background: #fff url(data:image/svg+xml;base64,PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0Ljk1IDEwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2ZmZjt9LmNscy0ye2ZpbGw6IzQ0NDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPmFycm93czwvdGl0bGU+PHJlY3QgY2xhc3M9ImNscy0xIiB3aWR0aD0iNC45NSIgaGVpZ2h0PSIxMCIvPjxwb2x5Z29uIGNsYXNzPSJjbHMtMiIgcG9pbnRzPSIxLjQxIDQuNjcgMi40OCAzLjE4IDMuNTQgNC42NyAxLjQxIDQuNjciLz48cG9seWdvbiBjbGFzcz0iY2xzLTIiIHBvaW50cz0iMy41NCA1LjMzIDIuNDggNi44MiAxLjQxIDUuMzMgMy41NCA1LjMzIi8+PC9zdmc+) no-repeat 100% 50%;

}

.btn {
    border-bottom-right-radius: 60px;
    border-top-right-radius: 60px;
    font-size: 15px;
    height: 60px;
    line-height: 60px;
    padding: 0;
    text-transform: uppercase;
    letter-spacing: .07em;
}
</style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
<div id="snow">
</div>


      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1><i class="glyphicon glyphicon-tree-conifer"></i> WIGGILIA! <i class="glyphicon glyphicon-tree-conifer"></i> </h1>
        <div class="row">
        <p class="lead">Wybierz <strong><u>SWOJE</u></strong> imię, a elfy św. Mikołaja zadecydują, komu przypadnie otrzymać prezent od Ciebie :)</p>
 		<div id="person-info-box"></div>

 		<form method="POST" action="?action=losuj" class="losowanie-form">
  		<select class=" col-xs-6" name="losujacy" style="margin-bottom:15px;">
  			<option value="select">(wybierz)</option>
  			<?php foreach($people as $item):?>
  				<option value="<?=$item->id;?>"><?=$item->name;?></option>
  			   <?php endforeach;?>
  	   </select>

  			<p><input type="submit" class=" col-xs-6 btn btn-lg btn-danger" role="button" value="Wysyłam zlecenie do Elfów!"></p></div>
  		</form>

      </div>
	</div>


    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
  <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src="js/jquery.form.js"></script>

  <script>
  var console = console || {log: function(){}};
$('#person-info-box').html("");
$(document).ready(function() {
    $('.losowanie-form').ajaxForm({
        dataType:  'json',
        success:   processJson
    });
});
/**
 * processJson - process data after ajax request
 *
 * @param  json data ajax request result
 */
function processJson(data) {
    $('#person-info-box').html("");
    // 'data' is the json object returned from the server
    //alert(data);
    $('#person-info-box').slideDown(2000).append('<div class="alert alert-success" role="alert">' + data + '</div>')

}
  </script>
<audio autoplay controls loop>
  <source src="lc.mp3" type="audio/mpeg">
  Twoja przeglądarka nie obsługuje elementu audio.
</audio>
</html>
